In [7]:
import pandas as pd

In [8]:
tracks_df = pd.read_json("tracks.json")
tracks_df.head()
tracks_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11166 entries, 0 to 11165
Data columns (total 37 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    11166 non-null  object
 1   id_artist             11166 non-null  object
 2   title                 11166 non-null  object
 3   featured_artists      3517 non-null   object
 4   primary_artist        11166 non-null  object
 5   language              11061 non-null  object
 6   album                 9652 non-null   object
 7   swear_IT              11166 non-null  int64
 8   swear_EN              11166 non-null  int64
 9   swear_IT_words        11166 non-null  object
 10  swear_EN_words        11166 non-null  object
 11  year                  10722 non-null  float64
 12  month                 9969 non-null   float64
 13  day                   9843 non-null   float64
 14  n_sentences           11090 non-null  float64
 15  n_tokens              11090 non-null  float64
 16  char_per_tok          11090 non-null  float64
 17  avg_token_per_clause  11090 non-null  float64
 18  bpm                   11102 non-null  float64
 19  rolloff               11102 non-null  float64
 20  flux                  11102 non-null  float64
 21  rms                   11102 non-null  float64
 22  flatness              11102 non-null  float64
 23  spectral_complexity   11102 non-null  float64
 24  pitch                 11102 non-null  float64
 25  loudness              11102 non-null  float64
 26  album_name            11088 non-null  object
 27  album_release_date    11088 non-null  object
 28  album_type            11088 non-null  object
 29  disc_number           11088 non-null  float64
 30  track_number          11088 non-null  float64
 31  duration_ms           11088 non-null  float64
 32  explicit              11088 non-null  float64
 33  popularity            11088 non-null  float64
 34  id_album              11088 non-null  object
 35  lyrics                11163 non-null  object
 36  streams@1month        11166 non-null  int64
dtypes: float64(20), int64(3), object(14)
memory usage: 3.2+ MB

In [23]:
artists_df = pd.read_json("../dataset/artists.json")
artists_df.head()
artists_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_author     104 non-null    object
 1   name          104 non-null    object
 2   gender        104 non-null    object
 3   birth_date    73 non-null     object
 4   birth_place   72 non-null     object
 5   nationality   71 non-null     object
 6   description   86 non-null     object
 7   active_start  50 non-null     object
 8   active_end    0 non-null      float64
 9   province      70 non-null     object
 10  region        68 non-null     object
 11  country       70 non-null     object
 12  latitude      72 non-null     float64
 13  longitude     72 non-null     float64
dtypes: float64(3), object(11)
memory usage: 11.5+ KB

In [11]:
#track id duplicati 

dup_track_ids = tracks_df["id"].duplicated(keep=False).sum()
print("Numero di righe con id duplicati:", dup_track_ids)

track_id_counts = tracks_df["id"].value_counts()
multi_track_ids = track_id_counts[track_id_counts > 1]

print("\nTrack ID che compaiono più di una volta:")
print(multi_track_ids)

track_duplicates = tracks_df[tracks_df["id"].isin(multi_track_ids.index)]
track_duplicates.sort_values("id").head(20)

Numero di righe con id duplicati: 144

Track ID che compaiono più di una volta:
id
TR367132    4
TR517220    2
TR761888    2
TR980497    2
TR597980    2
           ..
TR715264    2
TR423710    2
TR747430    2
TR261964    2
TR577214    2
Name: count, Length: 71, dtype: int64

,id,id_artist,title,featured_artists,primary_artist,language,album,swear_IT,swear_EN,swear_IT_words,...,album_release_date,album_type,disc_number,track_number,duration_ms,explicit,popularity,id_album,lyrics,streams@1month
4240,TR108862,ART56320683,Sushi Bar,None,Bassi Maestro,en,Sushi EP,8,1,"['bastardo', 'cesso', 'culo', 'fesso', 'merda']",...,2007-11-13,single,1.0,3.0,215461.0,1.0,6.0,ALB697589,Questo mondo resta freddo anche se vivi da sta...,5367
7786,TR108862,ART07127070,SPINE,Coez,Noyz Narcos,cs,VIRUS (Deluxe),1,0,['scopare'],...,2022-01-14,album,1.0,6.0,155294.0,1.0,44.0,ALB525038,Sei al centro del mio cuore come 'na spina\nSe...,17849
3199,TR135764,ART73965015,Nessuno vale quanto te,None,Ghemon,it,ORCHIdee,0,0,[],...,2014-05-27,album,1.0,8.0,238773.0,0.0,26.0,ALB346809,Dicono che da un posto piccolo non può venire ...,6875
5847,TR135764,ART86549066,Giovani eroi,Not Good,Emis Killa,it,"Keta Music, Vol. 3",5,1,"['bastardo', 'cazzo', 'merda', 'troia']",...,2021-07-23,album,1.0,10.0,152733.0,1.0,35.0,ALB168242,"Oh, la city è silenziosa, in zona solo un clac...",14390
8104,TR190585,ART78209349,Nei treni la notte,Frah Quintale,Coez,it,From The Rooftop 2,0,0,[],...,2022-10-14,album,1.0,3.0,181789.0,0.0,43.0,ALB760031,Ho fatto un giro in questa città\nEd è come fa...,5618
1570,TR190585,ART66932389,Serpico,Tiromancino,Piotta,pl,’na notte infame,0,0,[],...,2024-03-01,album,1.0,2.0,192994.0,0.0,21.0,ALB996374,Se c'avessi diciott'anni\nCo quer fuoco che c'...,5187
1947,TR192351,ART81071062,Tornerò Da Re - Redrum Version,None,Club Dogo,it,Vile Denaro - 10th Anniversary,1,0,['culo'],...,2007-05-17,album,2.0,4.0,244226.0,0.0,9.0,ALB390480,Quando ritornerò da te\nIo ci ritornerò da re\...,4307
2721,TR192351,ART88792008,Musica Commerciale,None,Jake La Furia,it,Musica Commerciale Deluxe Edition,8,0,"['cagare', 'cazzo', 'culo', 'figo', 'incazzare...",...,2013-01-01,album,1.0,1.0,163517.0,0.0,39.0,ALB145179,Permettete una parola che è da un po' che ho n...,11900
7938,TR205970,ART80977821,24.7,"Bassi Maestro, Guè",Jack The Smoker,it,V.Ita,4,0,"['figa', 'merda']",...,2009-10-10,album,1.0,6.0,240053.0,1.0,13.0,ALB704296,"Vivo questa roba, scrivo della merda che ti sv...",4733
8973,TR205970,ART08456301,Sigla Catteland,None,Rancore,it,None,0,0,[],...,2018-06-01,album,1.0,8.0,279213.0,0.0,42.0,ALB599065,"Stai su Deejay, su Radio Deejay\nQuesto è un a...",4173
2863,TR213881,ART07469279,Senza gravità,"Egreen, Jack The Smoker",Johnny Marsiglia,it,Orgoglio,1,0,['culo'],...,2012-09-28,album,1.0,3.0,214500.0,1.0,10.0,ALB357044,"Palermo, Varese, Milano\nJack The Smoker, John...",5179
7245,TR213881,ART85046033,Ti piacerebbe,"Primo Brown, Ensi",Gemitaiz,it,Quello Che Vi Consiglio Vol. 3,3,0,"['cazzo', 'figa', 'stronzo']",...,2018-03-30,album,1.0,8.0,207630.0,0.0,32.0,ALB565953,"Ha-Harsh Times\nYeah\n\nGuarda mamma, senza ma...",10177
141,TR230274,ART18853907,SaN LoREnZo,Annalisa,Alfa,it,NoRd,0,0,[],...,2021-05-14,album,1.0,6.0,202990.0,0.0,58.0,ALB472683,E quella volta tu sei andata sola\nCon un bigl...,5053
4964,TR230274,ART08177154,Per chi non ha un posto in questo mondo,None,Il Tre,it,ALI - ULTIMA NOTTE,1,0,['cazzo'],...,2021-02-19,album,1.0,1.0,193007.0,0.0,35.0,ALB399662,"Eh, piangerò\nMa le lacrime non fanno male a m...",19715
2050,TR237380,ART25707984,Alieno,None,Fabri Fibra,it,Squallor,0,0,[],...,2015-04-07,album,1.0,6.0,180500.0,1.0,39.0,ALB983527,Sono stato in cima alla vetta\nE mi sono scopa...,27188
5321,TR237380,ART40229749,S.O.S.,None,Baby K,None,S.O.S. EP,4,1,"['bastardo', 'fottuti', 'pene', 'stupida']",...,1962-04-10,album,1.0,8.0,142520.0,0.0,88.0,ALB261293,"Ah-ah\nMmm, okay!\nYooh\nIs Baby!\nSignore e s...",4573
2455,TR245683,ART48537029,Lo Sai Chi Siamo,Primo Brown,Mistaman,it,Parole,5,4,"['cazzi', 'cazzo', 'inculare', 'troia']",...,2004-01-14,album,1.0,9.0,202626.0,0.0,13.0,ALB902083,Ho imparato a ragionar con la mia testa\nGli z...,4291
9934,TR245683,ART78358659,Without You,None,Nitro,it,Danger,0,0,[],...,2013-07-16,album,1.0,10.0,218506.0,0.0,35.0,ALB610821,Gave up\nBut you said try just once more\nI ch...,34212
8708,TR247772,ART59609037,Finale Chimico,Ele A,Cor Veleno,it,Fuoco Sacro,0,0,[],...,2024-03-15,album,1.0,6.0,218337.0,0.0,30.0,ALB464615,Il primo giorno di scuola portavo le Reebok\nU...,4147
10077,TR247772,ART64850829,X Sempre,None,Shiva,it,Dark Love - EP,0,0,[],...,2022-06-24,album,1.0,5.0,205074.0,1.0,47.0,ALB772444,Mhm-mhm-mhm\nMhm-mhm-mhm\nUoh\n\nLa mia parte ...,9848

In [12]:
#album id duplicati
dup_album_ids = tracks_df["id_album"].duplicated(keep=False).sum()
print("Numero di righe con id_album duplicati:", dup_album_ids)

album_id_counts = tracks_df["id_album"].value_counts()
multi_album_ids = album_id_counts[album_id_counts > 1]

print("\nAlbum ID che compaiono più di una volta:")
print(multi_album_ids)

album_duplicates = tracks_df[tracks_df["id_album"].isin(multi_album_ids.index)]
album_duplicates.sort_values("id_album").head(20)

Numero di righe con id_album duplicati: 9016

Album ID che compaiono più di una volta:
id_album
ALB441104    48
ALB367028    45
ALB146392    41
ALB530526    37
ALB250335    34
             ..
ALB169428     2
ALB214026     2
ALB385130     2
ALB565861     2
ALB811166     2
Name: count, Length: 911, dtype: int64

,id,id_artist,title,featured_artists,primary_artist,language,album,swear_IT,swear_EN,swear_IT_words,...,album_release_date,album_type,disc_number,track_number,duration_ms,explicit,popularity,id_album,lyrics,streams@1month
4197,TR316763,ART56320683,Goditi La Vita,Rido MC,Bassi Maestro,it,Classe 73,8,0,"['bastardi', 'cazzo', 'mazzo']",...,2003-01-01,album,1.0,5.0,189000.0,1.0,13.0,ALB100033,Goditi la vita (Fino a che)\nNon è finita\n(Fi...,4584
4172,TR473781,ART56320683,Vinco io,None,Bassi Maestro,it,Classe 73,5,0,"['cazzo', 'merda', 'scazzo']",...,2003-01-01,album,1.0,1.0,196760.0,1.0,17.0,ALB100033,È il ritorno di... nah ritorno un cazzo\nÈ il ...,4904
4181,TR949559,ART56320683,Cosa Succede?!,Supa (CDB),Bassi Maestro,it,Classe 73,10,1,"['cazzo', 'fottere', 'merda']",...,2003-01-01,album,1.0,10.0,228106.0,1.0,15.0,ALB100033,"Ah-ah\nAh-ah (Yo)\nAh, ah, yo (Ehi)\n\nSembrav...",5362
4188,TR788344,ART56320683,Tu Lo Sai,None,Bassi Maestro,it,Classe 73,5,0,"['cazzi', 'incazzato', 'merda', 'stupido']",...,2003-01-01,album,1.0,2.0,191000.0,1.0,15.0,ALB100033,"Ehi, yo, la fuori\nB A doppia S I\nZero tre su...",5404
4097,TR832136,ART56320683,Giorni Matti,"Ape, Zampa",Bassi Maestro,it,Classe 73,1,0,['stupido'],...,2003-01-01,album,1.0,6.0,222000.0,1.0,46.0,ALB100033,Ehi\nDa tempo ho smesso di chiedermi il perché...,40091
4202,TR537753,ART56320683,Smiling Faces,None,Bassi Maestro,it,Classe 73,7,0,"['bastardi', 'cazzo', 'culo', 'fogna', 'merda']",...,2003-01-01,album,1.0,8.0,244000.0,1.0,12.0,ALB100033,"Il brano è prodotto da Mace.\n\nEhi, MACE, ple...",4266
4170,TR983017,ART56320683,Classe 73,None,Bassi Maestro,it,Classe 73,7,0,"['cazzi', 'cazzo', 'culo', 'merda']",...,2003-01-01,album,1.0,6.0,222000.0,1.0,46.0,ALB100033,"Non è quello che metti, ma come lo vesti\nNon ...",4367
4218,TR321247,ART56320683,Glory and Frustration,None,Bassi Maestro,it,Classe 73,5,2,"['cazzo', 'merda']",...,2003-01-01,album,1.0,3.0,169746.0,1.0,13.0,ALB100033,"Quanti debiti paghiamo, quanti ne ho pagati in...",5394
4153,TR730847,ART56320683,1-2-3 Pt.2,None,Bassi Maestro,it,Classe 73,7,0,"['cazzo', 'cesso', 'culo', 'merda', 'sfiga']",...,2003-01-01,album,1.0,4.0,183493.0,1.0,20.0,ALB100033,Hey Hakeem fratello!\nQuando sento questo cazz...,4728
4229,TR126928,ART56320683,The Cognac Sipper,None,Bassi Maestro,da,Classe 73,3,0,"['cazzi', 'cesso', 'merda']",...,2003-01-01,album,1.0,11.0,146760.0,1.0,12.0,ALB100033,"Ehi, yo, Hakeem\nCi sei B?\nAh-ah, ah-ah, yeah...",4393
4232,TR457607,ART56320683,Il Segreto,None,Bassi Maestro,it,Classe 73,0,0,[],...,2003-01-01,album,1.0,7.0,175906.0,1.0,12.0,ALB100033,"Ehi, vuoi il vero rap?\nPorta il cuore alle pa...",4731
4246,TR788822,ART56320683,Giuda (The Bad Seed),FK (FRA),Bassi Maestro,pl,Classe 73,8,7,"['cazzo', 'coglioni', 'puttana', 'vaffanculo']",...,2003-01-01,album,1.0,13.0,214000.0,1.0,9.0,ALB100033,"Eh, oh, eh, eh, tu fais quoi là ? Oh, eh, oh, ...",4515
4247,TR135597,ART56320683,La Vita È Maledetta,None,Bassi Maestro,it,Classe 73,5,0,"['cazzo', 'coglione', 'merda']",...,2003-01-01,album,1.0,12.0,182000.0,1.0,9.0,ALB100033,La vita è maledetta\nNon lo sai cosa t'aspetta...,4254
4285,TR736253,ART56320683,The show Off (Bonus Track),Rido MC,Bassi Maestro,pl,Classe 73,2,0,"['merda', 'toro']",...,2003-01-01,album,1.0,16.0,210680.0,1.0,6.0,ALB100033,Un anno fa un amico che ho\nVoleva organizzare...,5206
11070,TR551136,ART02733420,Bruce Willis,None,Marracash,it,Status (Vendetta Edition),0,0,[],...,2015-02-10,album,1.0,1.0,130546.0,1.0,34.0,ALB100713,Vengo da dove le sveglie suonano a tutti la st...,29832
11064,TR971836,ART02733420,In Radio,None,Marracash,en,Status (Vendetta Edition),0,0,[],...,2015-02-10,album,1.0,8.0,221881.0,1.0,59.0,ALB100713,Sorridi a questo flash che il mondo è qui per ...,30664
11061,TR612486,ART02733420,Bentornato,None,Marracash,it,Status (Vendetta Edition),6,2,"['bastardi', 'cazzo', 'culo', 'merda', 'scopat...",...,2015-02-10,album,1.0,2.0,208720.0,1.0,35.0,ALB100713,"Lotterò, lo otterrò e lo terrò per me\nMarraca...",33816
11087,TR714459,ART02733420,Vita Da Star,Fabri Fibra,Marracash,it,Status (Vendetta Edition),0,0,[],...,2015-02-10,album,1.0,4.0,236160.0,1.0,39.0,ALB100713,"Questa è un'altra hit, ah\nMarracash\n\nBaby, ...",24251
11094,TR996715,ART02733420,Crack,None,Marracash,it,Status (Vendetta Edition),2,0,"['culo', 'paraculo']",...,2015-02-10,album,1.0,13.0,292120.0,1.0,30.0,ALB100713,Lo diceva Beck: la sua prima track\nMTV fa ven...,20381
11078,TR528636,ART02733420,Di Nascosto,Guè,Marracash,pl,Status (Vendetta Edition),3,0,"['coglione', 'figa', 'ricchione']",...,2015-02-10,album,1.0,16.0,236840.0,1.0,37.0,ALB100713,"Baby, come riempi bene i jeans\nStreptococco p...",24145

In [13]:
# Duplicati perfetti: righe IDENTICHE su tutte le colonne
perfect_duplicates = tracks_df[tracks_df.duplicated(keep=False)]

print("Duplicati perfetti trovati:", len(perfect_duplicates))

perfect_duplicates.head(20)

Duplicati perfetti trovati: 0

Empty DataFrame
Columns: [id, id_artist, title, featured_artists, primary_artist, language, album, swear_IT, swear_EN, swear_IT_words, swear_EN_words, year, month, day, n_sentences, n_tokens, char_per_tok, avg_token_per_clause, bpm, rolloff, flux, rms, flatness, spectral_complexity, pitch, loudness, album_name, album_release_date, album_type, disc_number, track_number, duration_ms, explicit, popularity, id_album, lyrics, streams@1month]
Index: []

[0 rows x 37 columns]

In [14]:
# Prendiamo solo i track_id duplicati
track_id_counts = tracks_df["id"].value_counts()
multi_ids = track_id_counts[track_id_counts > 1].index

subset = tracks_df[tracks_df["id"].isin(multi_ids)].sort_values("id")

subset.head(20)

,id,id_artist,title,featured_artists,primary_artist,language,album,swear_IT,swear_EN,swear_IT_words,...,album_release_date,album_type,disc_number,track_number,duration_ms,explicit,popularity,id_album,lyrics,streams@1month
4240,TR108862,ART56320683,Sushi Bar,None,Bassi Maestro,en,Sushi EP,8,1,"['bastardo', 'cesso', 'culo', 'fesso', 'merda']",...,2007-11-13,single,1.0,3.0,215461.0,1.0,6.0,ALB697589,Questo mondo resta freddo anche se vivi da sta...,5367
7786,TR108862,ART07127070,SPINE,Coez,Noyz Narcos,cs,VIRUS (Deluxe),1,0,['scopare'],...,2022-01-14,album,1.0,6.0,155294.0,1.0,44.0,ALB525038,Sei al centro del mio cuore come 'na spina\nSe...,17849
3199,TR135764,ART73965015,Nessuno vale quanto te,None,Ghemon,it,ORCHIdee,0,0,[],...,2014-05-27,album,1.0,8.0,238773.0,0.0,26.0,ALB346809,Dicono che da un posto piccolo non può venire ...,6875
5847,TR135764,ART86549066,Giovani eroi,Not Good,Emis Killa,it,"Keta Music, Vol. 3",5,1,"['bastardo', 'cazzo', 'merda', 'troia']",...,2021-07-23,album,1.0,10.0,152733.0,1.0,35.0,ALB168242,"Oh, la city è silenziosa, in zona solo un clac...",14390
8104,TR190585,ART78209349,Nei treni la notte,Frah Quintale,Coez,it,From The Rooftop 2,0,0,[],...,2022-10-14,album,1.0,3.0,181789.0,0.0,43.0,ALB760031,Ho fatto un giro in questa città\nEd è come fa...,5618
1570,TR190585,ART66932389,Serpico,Tiromancino,Piotta,pl,’na notte infame,0,0,[],...,2024-03-01,album,1.0,2.0,192994.0,0.0,21.0,ALB996374,Se c'avessi diciott'anni\nCo quer fuoco che c'...,5187
1947,TR192351,ART81071062,Tornerò Da Re - Redrum Version,None,Club Dogo,it,Vile Denaro - 10th Anniversary,1,0,['culo'],...,2007-05-17,album,2.0,4.0,244226.0,0.0,9.0,ALB390480,Quando ritornerò da te\nIo ci ritornerò da re\...,4307
2721,TR192351,ART88792008,Musica Commerciale,None,Jake La Furia,it,Musica Commerciale Deluxe Edition,8,0,"['cagare', 'cazzo', 'culo', 'figo', 'incazzare...",...,2013-01-01,album,1.0,1.0,163517.0,0.0,39.0,ALB145179,Permettete una parola che è da un po' che ho n...,11900
7938,TR205970,ART80977821,24.7,"Bassi Maestro, Guè",Jack The Smoker,it,V.Ita,4,0,"['figa', 'merda']",...,2009-10-10,album,1.0,6.0,240053.0,1.0,13.0,ALB704296,"Vivo questa roba, scrivo della merda che ti sv...",4733
8973,TR205970,ART08456301,Sigla Catteland,None,Rancore,it,None,0,0,[],...,2018-06-01,album,1.0,8.0,279213.0,0.0,42.0,ALB599065,"Stai su Deejay, su Radio Deejay\nQuesto è un a...",4173
2863,TR213881,ART07469279,Senza gravità,"Egreen, Jack The Smoker",Johnny Marsiglia,it,Orgoglio,1,0,['culo'],...,2012-09-28,album,1.0,3.0,214500.0,1.0,10.0,ALB357044,"Palermo, Varese, Milano\nJack The Smoker, John...",5179
7245,TR213881,ART85046033,Ti piacerebbe,"Primo Brown, Ensi",Gemitaiz,it,Quello Che Vi Consiglio Vol. 3,3,0,"['cazzo', 'figa', 'stronzo']",...,2018-03-30,album,1.0,8.0,207630.0,0.0,32.0,ALB565953,"Ha-Harsh Times\nYeah\n\nGuarda mamma, senza ma...",10177
141,TR230274,ART18853907,SaN LoREnZo,Annalisa,Alfa,it,NoRd,0,0,[],...,2021-05-14,album,1.0,6.0,202990.0,0.0,58.0,ALB472683,E quella volta tu sei andata sola\nCon un bigl...,5053
4964,TR230274,ART08177154,Per chi non ha un posto in questo mondo,None,Il Tre,it,ALI - ULTIMA NOTTE,1,0,['cazzo'],...,2021-02-19,album,1.0,1.0,193007.0,0.0,35.0,ALB399662,"Eh, piangerò\nMa le lacrime non fanno male a m...",19715
2050,TR237380,ART25707984,Alieno,None,Fabri Fibra,it,Squallor,0,0,[],...,2015-04-07,album,1.0,6.0,180500.0,1.0,39.0,ALB983527,Sono stato in cima alla vetta\nE mi sono scopa...,27188
5321,TR237380,ART40229749,S.O.S.,None,Baby K,None,S.O.S. EP,4,1,"['bastardo', 'fottuti', 'pene', 'stupida']",...,1962-04-10,album,1.0,8.0,142520.0,0.0,88.0,ALB261293,"Ah-ah\nMmm, okay!\nYooh\nIs Baby!\nSignore e s...",4573
2455,TR245683,ART48537029,Lo Sai Chi Siamo,Primo Brown,Mistaman,it,Parole,5,4,"['cazzi', 'cazzo', 'inculare', 'troia']",...,2004-01-14,album,1.0,9.0,202626.0,0.0,13.0,ALB902083,Ho imparato a ragionar con la mia testa\nGli z...,4291
9934,TR245683,ART78358659,Without You,None,Nitro,it,Danger,0,0,[],...,2013-07-16,album,1.0,10.0,218506.0,0.0,35.0,ALB610821,Gave up\nBut you said try just once more\nI ch...,34212
8708,TR247772,ART59609037,Finale Chimico,Ele A,Cor Veleno,it,Fuoco Sacro,0,0,[],...,2024-03-15,album,1.0,6.0,218337.0,0.0,30.0,ALB464615,Il primo giorno di scuola portavo le Reebok\nU...,4147
10077,TR247772,ART64850829,X Sempre,None,Shiva,it,Dark Love - EP,0,0,[],...,2022-06-24,album,1.0,5.0,205074.0,1.0,47.0,ALB772444,Mhm-mhm-mhm\nMhm-mhm-mhm\nUoh\n\nLa mia parte ...,9848

In [16]:
#album incoerenti 
album_check = (
    tracks_df.groupby("id_album")[["album_name", "album_type", "primary_artist"]]
    .nunique()
)

problematic_albums = album_check[
    (album_check["album_name"] > 1) |
    (album_check["album_type"] > 1) |
    (album_check["primary_artist"] > 1)
]

print("\nAlbum con differenze nei campi chiave:")
problematic_albums.head(20)

Album con differenze nei campi chiave:

           album_name  album_type  primary_artist
id_album
ALB156429           2           1               2
ALB213075           1           2               1
ALB275546           2           1               2
ALB473208           2           2               2
ALB504235           2           2               2
ALB774561           1           2               1
ALB858106           1           2               1
ALB877400           2           2               2

In [18]:
#raggruppa tutte le righe per id_album raccoglie i valori unici di album_name, primary_artist, album_type
# filtra quelli che hanno valori multipli ➜ significa “stesso album ID ma album diversi”
#stampa il risultato in modo leggibile
#Serve a dimostrare che la chiave naturale id_album è sbagliata e non può essere usata come PK.
album_check = (
    tracks_df.groupby("id_album")
    .agg({
        "album_name": lambda x: list(x.dropna().unique()),
        "primary_artist": lambda x: list(x.dropna().unique()),
        "album_type": lambda x: list(x.dropna().unique())
    })
)

# Filtra solo quelli che hanno più di un valore
problematic_albums = album_check[
    album_check.apply(lambda row: 
        len(row["album_name"]) > 1 or
        len(row["primary_artist"]) > 1 or
        len(row["album_type"]) > 1,
        axis=1
    )
]

# Stampa con il formato desiderato
for idx, row in problematic_albums.iterrows():
    print(f"id_album: {idx}")
    print(f" - album_name: {row['album_name']}")
    print(f" - primary_artist: {row['primary_artist']}")
    print(f" - album_type: {row['album_type']}")
    print()

id_album: ALB156429
 - album_name: ['Ma Vaffanculo', "It's Snowing, Motherfucker"]
 - primary_artist: ['Skioffi', 'Rose Villain']
 - album_type: ['single']

id_album: ALB213075
 - album_name: ['Na.99.10']
 - primary_artist: ['99 Posse']
 - album_type: ['compilation', 'album']

id_album: ALB275546
 - album_name: ['La maggior parte', 'Poco di Buono']
 - primary_artist: ['Ghemon', 'Caneda']
 - album_type: ['album']

id_album: ALB473208
 - album_name: ['MALAVITA, Pt. 2 / HeadShot, Vol. 3', 'Il mio lato peggiore']
 - primary_artist: ['Inoki', 'Luchè']
 - album_type: ['single', 'album']

id_album: ALB504235
 - album_name: ['Affetto Illimitato', 'Handmade Cities']
 - primary_artist: ['Ensi', 'Entics']
 - album_type: ['album', 'single']

id_album: ALB774561
 - album_name: ['1990']
 - primary_artist: ['Achille Lauro']
 - album_type: ['album', 'single']

id_album: ALB858106
 - album_name: ['KINTSUGI']
 - primary_artist: ['Highsnob']
 - album_type: ['album', 'single']

id_album: ALB877400
 - album_name: ['Allora ciao', 'Red Bull 64 Bars, The Album']
 - primary_artist: ['Shade', 'Nitro']
 - album_type: ['single', 'compilation']

In [19]:


# Raggruppamento sui track_id problematici
track_check = (
    tracks_df.groupby("id")
    .agg({
        "title": lambda x: list(x.dropna().unique()),
        "primary_artist": lambda x: list(x.dropna().unique()),
        "album": lambda x: list(x.dropna().unique())
    })
)

# Filtra solo quelli con valori multipli (incoerenti)
problematic_tracks = track_check[
    track_check.apply(lambda row:
        len(row["title"]) > 1 or
        len(row["primary_artist"]) > 1 or
        len(row["album"]) > 1,
        axis=1
    )
]

# Stampa in formato leggibile
for idx, row in problematic_tracks.iterrows():
    print(f"track_id: {idx}")
    print(f" - title: {row['title']}")
    print(f" - primary_artist: {row['primary_artist']}")
    print(f" - album: {row['album']}")
    print()

track_id: TR108862
 - title: ['Sushi Bar', 'SPINE']
 - primary_artist: ['Bassi Maestro', 'Noyz Narcos']
 - album: ['Sushi EP', 'VIRUS (Deluxe)']

track_id: TR135764
 - title: ['Nessuno vale quanto te', 'Giovani eroi']
 - primary_artist: ['Ghemon', 'Emis Killa']
 - album: ['ORCHIdee', 'Keta Music, Vol. 3']

track_id: TR190585
 - title: ['Serpico', 'Nei treni la notte']
 - primary_artist: ['Piotta', 'Coez']
 - album: ['’na notte infame', 'From The Rooftop 2']

track_id: TR192351
 - title: ['Tornerò Da Re - Redrum Version', 'Musica Commerciale']
 - primary_artist: ['Club Dogo', 'Jake La Furia']
 - album: ['Vile Denaro - 10th Anniversary', 'Musica Commerciale Deluxe Edition']

track_id: TR205970
 - title: ['24.7', 'Sigla Catteland']
 - primary_artist: ['Jack The Smoker', 'Rancore']
 - album: ['V.Ita']

track_id: TR213881
 - title: ['Senza gravità', 'Ti piacerebbe']
 - primary_artist: ['Johnny Marsiglia', 'Gemitaiz']
 - album: ['Orgoglio', 'Quello Che Vi Consiglio Vol. 3']

track_id: TR230274
 - title: ['SaN LoREnZo', 'Per chi non ha un posto in questo mondo']
 - primary_artist: ['Alfa', 'Il Tre']
 - album: ['NoRd', 'ALI - ULTIMA NOTTE']

track_id: TR237380
 - title: ['Alieno', 'S.O.S.']
 - primary_artist: ['Fabri Fibra', 'Baby K']
 - album: ['Squallor', 'S.O.S. EP']

track_id: TR245683
 - title: ['Lo Sai Chi Siamo', 'Without You']
 - primary_artist: ['Mistaman', 'Nitro']
 - album: ['Parole', 'Danger']

track_id: TR247772
 - title: ['Finale Chimico', 'X Sempre']
 - primary_artist: ['Cor Veleno', 'Shiva']
 - album: ['Fuoco Sacro', 'Dark Love - EP']

track_id: TR261964
 - title: ['Jezuz', 'Dove Sarai Tu']
 - primary_artist: ['Salmo', 'Mondo Marcio']
 - album: ['Mr. Antipatia', 'Nella Bocca Della Tigre']

track_id: TR282769
 - title: ['Loser', 'Nisciun']
 - primary_artist: ['Nerone', 'Luchè']
 - album: ['PENKILLER', 'Malammore']

track_id: TR292480
 - title: ['Boogie Loogie Bpm', 'Nel mio piccolo']
 - primary_artist: ['Neffa', 'Fedez']
 - album: ['107 elementi', 'Sig. Brainwash - L’arte di accontentare Diamond Edition']

track_id: TR318448
 - title: ['Scimmia', 'Roby Esce A Maggio']
 - primary_artist: ['Mudimbi', 'Caneda']
 - album: ['Michel']

track_id: TR323298
 - title: ['Ex Contadino', 'Veleno 7']
 - primary_artist: ['Dargen D’Amico', 'Gemitaiz']
 - album: ['Di vizi di forma virtù', 'Scatola nera']

track_id: TR324280
 - title: ['Christian Rap RMX (Freestyle)', 'La tua anima che balla']
 - primary_artist: ['Lazza', 'Cor Veleno']
 - album: ['Meme K Ultra']

track_id: TR362754
 - title: ['Old man', 'Blu']
 - primary_artist: ['Nerone', 'Grido']
 - album: ['MAXTAPE', 'Segnali di Fumo']

track_id: TR367132
 - title: ['BUGIE', '\u200bsentimi']
 - primary_artist: ['Madame']
 - album: ['MADAME']

track_id: TR371139
 - title: ['Faccio un casino (TJ Unicorno Extended Mix)', 'Sempre in serata']
 - primary_artist: ['Coez', 'Mondo Marcio']
 - album: ['Faccio un casino (TJ Unicorno Remix) - Single', 'Cose Dell’Altro Mondo Mondo Marcio: Special Edition']

track_id: TR383581
 - title: ['Equilibrio', 'Gravità']
 - primary_artist: ['Entics', 'Frah Quintale']
 - album: ['Soundboy', 'Lungolinea.']

track_id: TR386339
 - title: ['Maria Antonietta (Re-Edit)', 'Eden1']
 - primary_artist: ['Priestess', 'Caneda']
 - album: []

track_id: TR388228
 - title: ['Punto G', 'Va tutto bene']
 - primary_artist: ['Luchè', 'Coez']
 - album: ['Il mio lato peggiore', 'Fenomeno Mixtape']

track_id: TR420065
 - title: ['Supercalifrigida', 'Senza mani']
 - primary_artist: ['Mudimbi', 'Coez']
 - album: ['Senza mani - EP']

track_id: TR423710
 - title: ['Ancora E Ancora', 'Perdendo il controllo']
 - primary_artist: ['Brusco', 'Mondo Marcio']
 - album: ['Brusco', 'In Cosa Credi']

track_id: TR427122
 - title: ['Fammi Accendere', 'No Rmx']
 - primary_artist: ['Cor Veleno', 'Caneda']
 - album: ['\u200eRock ‘N’ Roll']

track_id: TR448308
 - title: ['Lascia Un Segno', 'Città Di Vetro']
 - primary_artist: ['Fabri Fibra', 'Cor Veleno']
 - album: ['Il tempo vola 2002-2020', 'Lo Spirito Che Suona']

track_id: TR458543
 - title: ['Maxtape Soprano', 'Di Nascosto (Don Joe Demo 2014)']
 - primary_artist: ['Nerone', 'Marracash']
 - album: ['Status (Vendetta Edition)']

track_id: TR464052
 - title: ['I Soldi Parlano', 'Polvere']
 - primary_artist: ['Capo Plaza', 'Shiva']
 - album: ['PLAZA (Deluxe Edition)', 'Solo']

track_id: TR475283
 - title: ['Sei Cannibale Ma Non Sei Cattiva', 'Tranquillo 2021']
 - primary_artist: ['Dargen D’Amico', 'Sottotono']
 - album: ['NEI SOGNI NESSUNO È MONOGAMO', 'Originali']

track_id: TR497887
 - title: ['Savage', 'Killer Game']
 - primary_artist: ['Nerone', 'Salmo']
 - album: ['MAXTAPE', 'Midnite (Deluxe Version)']

track_id: TR503521
 - title: ['E Tu Ci Convivi', 'In TV i film più belli li fanno sempre di notte']
 - primary_artist: ['Fabri Fibra', 'Caneda']
 - album: ['Squallor']

track_id: TR517220
 - title: ['Fyah', 'In Quel Posto']
 - primary_artist: ['Babaman', 'Fabri Fibra']
 - album: ['Dinamite', 'Chi Vuole Essere Fabri Fibra?']

track_id: TR531651
 - title: ['Serenata - From “Forever Out of My League”', 'MUSICA ETERNA']
 - primary_artist: ['Alfa', 'Grido']
 - album: ['MUSICA ETERNA']

track_id: TR534818
 - title: ['COL CUORE IN GOLA (lords of dogtown)', 'Sigarette']
 - primary_artist: ['Emis Killa', 'Mondo Marcio']
 - album: ['Effetto notte (L’alba)', 'My Beautiful Bloody Break Up - Full Circle']

track_id: TR577214
 - title: ['Herrera', 'Il tuo nome - Acoustic Version']
 - primary_artist: ['YEИDRY', 'Il Tre']
 - album: ['ALI - ULTIMA NOTTE']

track_id: TR597980
 - title: ['La confessione', 'LEWANDOWSKI VIII (64 Bars)']
 - primary_artist: ['Bassi Maestro', 'Ernia']
 - album: ['Classico', 'RED BULL 64 BARS, The Album']

track_id: TR621186
 - title: ['IDGAF', 'PELLE D’OCA']
 - primary_artist: ['Vacca', 'Don Joe']
 - album: ['DON DADA']

track_id: TR638268
 - title: ['Parole Da Dedicarmi', 'Lento RMX']
 - primary_artist: ['Nesli', 'MamboLosco']
 - album: ['Ego', 'Caldo ']

track_id: TR679972
 - title: ['Fuoriluogo ovunque', 'Continua Domani']
 - primary_artist: ['Ghemon', 'Mondo Marcio']
 - album: ['ORCHIdee', 'Puoi Fare di Meglio!!!']

track_id: TR690925
 - title: ['BlaBlaBla', 'Drink Lungo']
 - primary_artist: ['MamboLosco', 'Achille Lauro']
 - album: ['Facendo Faccende', 'Achille Idol Immortale']

track_id: TR715264
 - title: ['\u200bnon è normale', 'Amore lo-fi']
 - primary_artist: ['Rosa Chemical', 'Clementino']
 - album: ['Black Pulcinella']

track_id: TR716382
 - title: ['Andiamo A Lavorare', 'Storie che non esistono']
 - primary_artist: ['Articolo 31', 'Neffa']
 - album: ['Messa di Vespiri', 'Molto Calmo']

track_id: TR726762
 - title: ['2+2', 'Rellapiras']
 - primary_artist: ['Rondodasosa', 'Slait']
 - album: ['BLUE TAPE', 'BV2']

track_id: TR731836
 - title: ['MILAN FREESTYLE*', 'Rispetto di tutti, paura di nessuno']
 - primary_artist: ['Tedua', 'Ensi']
 - album: ['Rock Steady']

track_id: TR737119
 - title: ['Shawty', 'Patto Di Fango']
 - primary_artist: ['Yung Snapp', 'Dargen D’Amico']
 - album: ['HOTEL MONTANA (Deluxe)', 'Ciao America']

track_id: TR743448
 - title: ['Particolare', 'Angelo In Terra']
 - primary_artist: ['thasup', 'Johnny Marsiglia']
 - album: ['Fantastica Illusione']

track_id: TR747430
 - title: ['Sotto tiro', 'Scooteroni']
 - primary_artist: ['Tony Boy', 'Marracash']
 - album: ['TRVPPIN’ BOYZ', 'Santeria (Voodoo Edition)']

track_id: TR750485
 - title: ['Your World', 'Parli di rap?']
 - primary_artist: ['Shablo', 'Fedez']
 - album: ['The Second Feeling', 'Il mio primo disco da venduto']

track_id: TR754440
 - title: ['Bubble Gum (버블검)', 'Tatuaggio']
 - primary_artist: ['BigMama', 'Jack The Smoker']
 - album: ['Game Over Mixtape vol. 1']

track_id: TR757765
 - title: ['La story infinita', 'Uno a Cento']
 - primary_artist: ['Tedua', 'Mondo Marcio']
 - album: ['Vita vera mixtape: Aspettando la Divina Commedia', 'Puoi Fare di Meglio!!!']

track_id: TR761888
 - title: ['ATTO II', 'Pezzo Trap']
 - primary_artist: ['Nerone', 'Gemitaiz']
 - album: ['Davide']

track_id: TR772702
 - title: ['MANDANTE', 'Il Motivo']
 - primary_artist: ['Rondodasosa', 'Mondo Marcio']
 - album: ['Solo Un Uomo (Gold Edition)']

track_id: TR798937
 - title: ['Non Parlarmi (Outro)', 'Mainstream (La scala sociale del Rap)']
 - primary_artist: ['Massimo Pericolo', 'J-Ax']
 - album: ['Le cose cambiano (Deluxe)', 'SurreAle']

track_id: TR809682
 - title: ['LETTERA DEL MONDO ALL’UMANITÀ', 'Lemon Haze']
 - primary_artist: ['Achille Lauro', 'Dani Faiv']
 - album: ['LAURO (Deluxe Version)', 'Fruit Joint + Gusto']

track_id: TR825208
 - title: ['L’ho fatto per te', 'Senza Dio']
 - primary_artist: ['Tormento', 'Fred De Palma']
 - album: ['Il Mio Diario: Giorno', 'Unico']

track_id: TR844214
 - title: ['Successo', 'Interludio (L’Avvelenata)']
 - primary_artist: ['Mistaman', 'Willie Peyote']
 - album: ['M-Theory', 'Educazione Sabauda']

track_id: TR866344
 - title: ['L’italiano balla', 'Hip Hop Market']
 - primary_artist: ['Fabri Fibra', 'Bassi Maestro']
 - album: ['L’Italiano Balla', 'Hate']

track_id: TR869063
 - title: ['Fenomeno', 'Cosa?']
 - primary_artist: ['Ernia', 'Dark Polo Gang']
 - album: []

track_id: TR895238
 - title: ['Dubai (Why, Oh Why)', 'Il Circo Delle Pantegane']
 - primary_artist: ['Neffa', 'Caparezza']
 - album: ['Resistenza Edizione Speciale', 'Le Dimensioni Del Mio Caos']

track_id: TR896087
 - title: ['Ok', 'HELLVISBACK 2']
 - primary_artist: ['Tony Boy', 'Salmo']
 - album: ['Going Hard', 'FLOP']

track_id: TR898853
 - title: ['\u200boh 9od', 'Freestyle ft. Bassi Maestro (NewKingzTape)']
 - primary_artist: ['thasup', 'Inoki']
 - album: ['23 6451', 'The NewKingzTape Vol. 1']

track_id: TR903275
 - title: ['D.J. Jad', 'Magazine']
 - primary_artist: ['Articolo 31', 'Dark Polo Gang']
 - album: ['Strade di Città', 'Twins']

track_id: TR922726
 - title: ['Stop That Train', 'Segnali Di Fumo']
 - primary_artist: ['Guè', 'Grido']
 - album: ['Rimo Da Quando', 'Segnali di Fumo']

track_id: TR925275
 - title: ['Amor de mi vida (Amazon Music Original)', 'Bimbo Speciale']
 - primary_artist: ['Shablo', 'Fedez']
 - album: ['Tutto il Contrario Remixtape']

track_id: TR938316
 - title: ['64 BARRE DI VERITÀ (Red Bull 64 Bars)', 'Dillo Un’altra Volta']
 - primary_artist: ['Tony Effe', 'Cor Veleno']
 - album: ['Nuovo Nuovo']

track_id: TR970205
 - title: ['Silent Hill', 'GIÀ LO SAI']
 - primary_artist: ['Skioffi', 'Geolier']
 - album: ['DIO LO SA - ATTO II']

track_id: TR976686
 - title: ['Ibridi', 'Passo e chiudo']
 - primary_artist: ['Beba', 'Bassi Maestro']
 - album: ['Joker Mixtape', 'Background ']

track_id: TR978886
 - title: ['Ode Con Creta', 'L’arte di accontentare']
 - primary_artist: ['Dargen D’Amico', 'Fedez']
 - album: ['L’ottavia', 'Sig. Brainwash - L’arte di accontentare Diamond Edition']

track_id: TR980497
 - title: ['Andiamo', 'Te-le-co-man-do']
 - primary_artist: ['Nerone', 'Mistaman']
 - album: ['100k EP', 'Anni senza fine']

track_id: TR987615
 - title: ['Polo Nord', 'Django Muzik']
 - primary_artist: ['Massimo Pericolo', 'Bassi Maestro']
 - album: ['Guarda In Cielo']

track_id: TR997536
 - title: ['L’oracolo di Selfie', 'Vida Loca']
 - primary_artist: ['Nitro', 'Mondo Marcio']
 - album: ['Suicidol - Post Mortem', 'UOMO!']

In [20]:
# Set degli artisti presenti nei brani
track_artists = set(tracks_df["id_artist"].dropna().unique())

# Set degli artisti presenti nella tabella artisti
artist_ids = set(artists_df["id_author"].dropna().unique())

# Artisti usati nelle tracce ma assenti nella tabella artist
missing_artists = track_artists - artist_ids

print("Numero di artisti usati nelle tracce MA NON presenti in artist.xml:", len(missing_artists))
list(missing_artists)[:20]

Numero di artisti usati nelle tracce MA NON presenti in artist.xml: 0

[]

In [21]:
artist_check = (
    tracks_df.groupby("id_artist")["primary_artist"]
    .nunique()
    .reset_index(name="count_primary_artist")
)

problematic_artist_ids = artist_check[artist_check["count_primary_artist"] > 1]

print("Artisti con ID incoerente:", len(problematic_artist_ids))
problematic_artist_ids.head(20)

Artisti con ID incoerente: 0

Empty DataFrame
Columns: [id_artist, count_primary_artist]
Index: []

In [22]:
import os
os.getcwd()

'c:\\Users\\Win10\\OneDrive - Università degli Studi di Torino\\Desktop\\repo_dss\\dss_lab_project\\assignment_3'

In [24]:
import pandas as pd
import re

# Estrai la colonna dei featuring
feat_series = tracks_df["featured_artists"].dropna()

# Pattern valido: solo artisti separati da virgola
valid_pattern = r'^\s*[^,]+(\s*,\s*[^,]+)*\s*$'

# Trova le righe NON valide
invalid_feat = feat_series[~feat_series.astype(str).str.match(valid_pattern)]

print("Numero di featuring NON separati correttamente da virgola:", len(invalid_feat))
invalid_feat.head(20)

Numero di featuring NON separati correttamente da virgola: 0

Series([], Name: featured_artists, dtype: object)

In [25]:
featuring_with_amp = tracks_df[
    tracks_df["featured_artists"].astype(str).str.contains("&", na=False)
]

print("Numero di tracce con '&' nei featuring:", len(featuring_with_amp))
featuring_with_amp[["title", "featured_artists"]].head(20)

Numero di tracce con '&' nei featuring: 9

                                    title                  featured_artists
1566                     Comunque vada...                    Turi & Compari
2427                          Musica Vera                 Stokka & MadBuddy
2461  Il giorno in cui ci siamo svegliati                 Stokka & MadBuddy
2645                     Lo Facciamo Così                 Stokka & MadBuddy
2844                               Dreams                 Stokka & MadBuddy
3301                                 Pace   Stokka & MadBuddy, Franco Negrè
3616                         ’O Sarracino  Giuliano Palma & The Bluebeaters
5576                              CHIAGNE             Lazza, Takagi & Ketra
9095                              DONDURÈ                         Ski & Wok

In [26]:
primary_with_amp = tracks_df[
    tracks_df["primary_artist"].astype(str).str.contains("&", na=False)
]

print("Numero di tracce con '&' nel primary_artist:", len(primary_with_amp))
primary_with_amp[["title", "primary_artist"]].head(20)

Numero di tracce con '&' nel primary_artist: 0

Empty DataFrame
Columns: [title, primary_artist]
Index: []